### ISSUE TITLE
Disable Drag-Down Row Add

### ISSUE THREAD

**Issue by fromMUFCwithluv** [jrowen/rhandsontable#136]
Hi,

I have a feature request...would it be possible to have a way to disable adding rows to an rhandsontable  by selecting a cell, clicking on the bottom right corner and dragging down? Am trying to stop other users from editing the dimensions of the table and this would be very useful!

Of course if there already is an option then I've just been bad at finding it!

Regards,
Ashley

**Comment by jrowen** [comment]
You can try passing fillHandle = FALSE to rhandsontable.  Let me know if that doesn't work.

http://docs.handsontable.com/0.29.1/demo-drag-down.html

On December 19, 2016, at 10:14 AM, fromMUFCwithluv <notifications@github.com> wrote:

Hi,

I have a feature request...would it be possible to have a way to disable adding rows to an rhandsontable by selecting a cell, clicking on the bottom right corner and dragging down? Am trying to stop other users from editing the dimensions of the table and this would be very useful!

Of course if there already is an option then I've just been bad at finding it!

Regards,
Ashley

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jrowen/rhandsontable","title":"jrowen/rhandsontable","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/jrowen/rhandsontable">https://github.com/jrowen/rhandsontable</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Disable Drag-Down Row Add (#136)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/jrowen/rhandsontable/issues/136">https://github.com/jrowen/rhandsontable/issues/136</a>"}}}

**Comment by fromMUFCwithluv** [comment]
Thanks, it works :) Thought it would be me not searching properly!
