### ISSUE TITLE
Button that fills a given column with variables

### ISSUE THREAD

**Issue by bartekli** [jrowen/rhandsontable#187]
Hi,

I would like to prepare a Shiny App with rhandsontable package.
My question is how to make a button that, after clicking, generates a string of variables (e.g. var<-runif(10,0,1)) and fills with it a given column (let's assume: Col2) of an already existing table?

A sample code without this button is like this:

```
library(rhandsontable)
library(shiny)
# add a sparkline chart
DF$chart = sapply(1:10, function(x) jsonlite::toJSON(list(values=rnorm(10))))
rhandsontable(DF, rowHeaders = NULL) %>%
  hot_col("chart", renderer = htmlwidgets::JS("renderSparkline"))

editTable <- function(DF, outdir=getwd(), outfilename="table"){
  ui <- shinyUI(fluidPage(
  titlePanel("Edit and save a table"),
    sidebarLayout(
      sidebarPanel(
        helpText("Shiny app based on an example given in the rhandsontable package.", 
                 "Right-click on the table to delete/insert rows.", 
                 "Double-click on a cell to edit"),
        
 wellPanel(
          h3("Table options"),
          radioButtons("useType", "Use Data Types", c("TRUE", "FALSE"))
        ),
        br(), 
        
 wellPanel(
          h3("Save"), 
          actionButton("save", "Save table")
        ),    
        
        wellPanel(
          textOutput('result')
        ) 
      ),
      
      mainPanel(
         rHandsontableOutput("hot")
      )
    )
    ))
   server <- shinyServer(function(input, output) {
    
    values <- reactiveValues()
    
    ## Handsontable
    observe({
      if (!is.null(input$hot)) {
        DF = hot_to_r(input$hot)
      } else {
        if (is.null(values[["DF"]]))
          DF <- DF
        else
          DF <- values[["DF"]]
      }
      values[["DF"]] <- DF
    })
    
    output$hot <- renderRHandsontable({
      DF <- values[["DF"]]
      if (!is.null(DF))
        rhandsontable(DF, useTypes = as.logical(input$useType), stretchH = "all")
    })
    
    ## Save 
    observeEvent(input$save, {
      finalDF <- isolate(values[["DF"]])
      saveRDS(finalDF, file=file.path(outdir, sprintf("%s.rds", outfilename)))
    })
   
  })
  
  ## run app 
  runApp(list(ui=ui, server=server))
  function(input, output)
    return(invisible())
}

( DF <- data.frame(Col1=1:10, Col2=runif(10), stringsAsFactors = FALSE))

editTable(DF)
```

I would be grateful for any help!

**Comment by Paul-A-Kavan** [comment]
I know this post is old but here is a solution in case anyone else comes across this. 

Put the data in a reactive value so that the table refreshes upon data changes.
Then use the hot selectCallback option to retrieve selected cell location inside of the button observer. 
Finally, use the selected cell coordinates to change the value in the reactive data set.
Below is a minimal example:

library(rhandsontable)
library(shiny)

DF <- data.frame(col1 = 1:10, col2 = rnorm(10))

ui <- shinyUI(fluidPage(
  titlePanel("Edit cell in rhandsontable with a shiny button"),
  sidebarLayout(
    sidebarPanel(
      actionButton("save", "Save table"),
      actionButton("changeValue_button", "Change a cell value")),
      mainPanel(
        rHandsontableOutput("hot")
      ))))

server <- shinyServer(function(input, output, session) {
  
  # put the data in reactive values so rhandsontbale refreshes automatically
  values <- reactiveValues(tableData = DF) 
  
  output$hot <- renderRHandsontable({
    req(values$tableData)
    # make sure to turn on select callbacks to get the selected cell
    rhandsontable(values$tableData, selectCallback = T)
  })
  
  # observer to change cell value when button is clicked
  observeEvent(input$changeValue_button, { 
    rowSel <- input$hot_select$select$r # get selected row
    colSel <- input$hot_select$select$c # get selected column
    # to change a selected area of table you'll also need:
    # rowSel2 <- input$hot_select$select$r2
    # colSel2 <- input$hot_select$select$c2
    
    newValue = 10000
    
    # assigning back to reactive data set will trigger table refresh
    values$tableData[rowSel,colSel] <- newValue 
  })
})

## run app 
runApp(list(ui=ui, server=server))
