### ISSUE TITLE
Change invalid cell color from red to a different color

### ISSUE THREAD

**Issue by parkerac** [jrowen/rhandsontable#261]
Hi jrowen,
I really like the functionality of rhandsontable, especially the dropdown option for editing cells in the table. I am using rhandsontable in a shiny app and allow the user to enter invalid values. I like that rhandsontable changes color to indicate that the value is not in the source, but I would really like it if the background was something other than red so it doesn't look like there is something wrong. I tried using conditional formatting to change the color of the cells, but the red error always overrides. Is there anyway to change this?
Thanks!

**Comment by Paul-A-Kavan** [comment]
Hi parkerac! Could you post the renderer that you tried for the conditional formatting?

**Comment by parkerac** [comment]
Below is what I tried. I made my if statement just say "value == value" so I knew that everything in that column should be pink. The cells were indeed pink, but when I entered an invalid entry, the cells turned red. 

rhandsontable(editNewData, useTypes = F, selectCallback = T, stringsAsFactors = F) %>%
        hot_col(col = "Current Name", readOnly = T, type = "text") %>%
        hot_col(col = "Thesaurus Name", type = "dropdown", source = c(NA, thesaurus$"NCIt Preferred Name"), allowInvalid = T) %>%
        hot_col(col = "Delete", type = "checkbox") %>%
        hot_table(contextMenu = F) %>%
        hot_col(col = "Thesaurus Name", renderer = "
                function (instance, td, row, col, prop, value, cellProperties) {
                Handsontable.renderers.NumericRenderer.apply(this, arguments);
                if (value == value) {
                td.style.background = 'pink';
                } else {
                td.style.background = 'white';
                td.style.color = 'black';
                }
                
                }")
      })

**Comment by Paul-A-Kavan** [comment]
Okay, it turns out we shouldn't need the renderer... after a bit more digging I found that handsontable puts a specific class attribute on the invalidated td cells as seen in this css from handsontable.css:
`
.handsontable td.htInvalid {
  background-color: #ff4c42 !important; /*gives priority over td.area selection background*/
}
`

>  but the red error always overrides.
The reason the red overrides your renderer's new color is because css gets the final say on styling the html. 

A possible solution is to create your own css. In your shiny app, include www/style.css and inside this style sheet you can include the css code above but with your own color. Normally, we would try to avoid using !important but handsontable used it which means we have no choice either. And finally, I believe the shiny style sheet will have precedence over handsontable's so the issue should be solved. Let me know how it goes!

**Comment by parkerac** [comment]
Thank you so much! That worked perfectly!
