### ISSUE TITLE
Date Validation

### ISSUE THREAD

**Issue by him4u324** [jrowen/rhandsontable#266]
Hello, Please help with an alternate to put validation on Date picker column.

**Comment by him4u324** [comment]
Hello Paul, I am not much familiar with javascript. I wanted that user should not be able to select any date prior to current date. as of now we have numeric and character validator but not for dates.

**Comment by Paul-A-Kavan** [comment]
There might be a way to do this with the handsontable package but that will require some work on the R package to extend functionality. I will make a note to look into this extension when I have some free time. But for now lets figure out a possible solution. I think the simplest way will be a javascript validator. We simply write a new validator to do the job and you just need to include it in your R code. Take a look at the code below and let me know if you have questions!

```
library(shiny)
library(rhandsontable)
ui <- fluidPage(
  rHandsontableOutput("hot")
)
server <- function(input, output) {
  rvals <- reactiveValues(df = data.frame(
    Var1=seq(Sys.Date(), Sys.Date()+365, by='month'), 
    Var2=0:12))
  
  output$hot <- renderRHandsontable({
      rhandsontable(rvals$df) %>% 
        hot_cols(colWidths = c(150,50)) %>% 
        hot_col(1, strict=T, allowInvalid=T,
                validator = "function (value, callback) {
                var today_date = new Date();
                var new_date = new Date(value);
                try {
                if ( new_date.getFullYear() < today_date.getFullYear() ) {
                callback( false ); return;
                } 
                if ( new_date.getFullYear() > today_date.getFullYear() ) {
                callback( true ); return;
                } 
                if ( new_date.getMonth() < today_date.getMonth() ) {
                callback( false ); return;
                }
                if ( new_date.getMonth() > today_date.getMonth() ) {
                callback( true ); return;
                }
                if ( new_date.getDay() >= today_date.getDay() ) {
                callback( true ); return;
                }
                } catch(err) { console.log(err); }
                callback( false );
    }")
  })
  }
shinyApp(ui = ui, server = server)
```
A quick note of a bug:
Don't use this with allowInvalid = F because it will close the date picker but not let you leave the cell then the only solution is to use CTL+z to put a safe value back in.

**Comment by jrowen** [comment]
Please re-open is this is still an issue.
