### ISSUE TITLE
NA and NaN values break column types

### ISSUE THREAD

**Issue by mbacou** [jrowen/rhandsontable#30]
Hi, very useful JS bindings!
I just noticed that when numeric columns contain NA or NaN values, then the renderer breaks (reads numeric columns as text). In that case I have to manually set column types and formats. Is this behavior by  design? Also I'm wondering what's the best way to render NA and NaN to something nicer on the client, like "--" or "no data", etc.
Thanks, --Mel.

**Comment by jrowen** [comment]
Thanks for reporting, can you share an example of some brief steps to reproduce?

I just took a look at
```
shiny::runGitHub("rhandsontable", "jrowen", subdir = "inst/examples/rhandsontable_output")
```
adding NA to the first column in the initial data.frame, and it remains an integer type.  Deleting data in a cell (i.e. creating a blank cell) changes that value to NA and also doesn't seem to change the column class.  Are you using the `hot_to_r` function to convert the JS data to an R data.frame?

I was also just looking at a cleaner way to render NAs, and I'm open to suggestions.  To display blank cells instead of NA, the column will have to change to character for the JS (likely in `hot_table`) and then back to numeric in R (via `hot_to_r`).  I want to first see if there is a way to handle this natively in handsontable.js.

**Comment by mbacou** [comment]
Yes, please see test here http://tools.harvestchoice.org/cell5mValidate/testHS.Rmd (trying to print a random `df` data.table). The exact code shows above each table. The first call does not render the 4 numeric variables as I'd expect.

**Comment by jrowen** [comment]
Could you add `dput(df)` at the end of your example so I can test with your actual dataset?  Thanks.

**Comment by mbacou** [comment]
Sorry for the wait, just did. Thx for the help.

**Comment by jrowen** [comment]
For now, I think something like the sample below will work for converting NA to empty strings.
```
DF = data.frame(val = c(1:9, NA), bool = TRUE, nm = LETTERS[1:10],
                dt = seq(from = Sys.Date(), by = "days", length.out = 10),
                stringsAsFactors = F)

rhandsontable(DF) %>%
  hot_col("val", renderer = htmlwidgets::JS(
    "function(instance, TD, row, col, prop, value, cellProperties) {
      if (value === 'NA') {
        value = '';
        Handsontable.renderers.TextRenderer(instance, TD, row, col, prop, value, cellProperties);
      } else {
        Handsontable.renderers.NumericRenderer(instance, TD, row, col, prop, value, cellProperties);
      }
    }")
  )
```
Currently the default logic converts all classes to string when sending to handsontable, as this displays the same numeric precision as R.  It might be possible to get a bit smarter here, which will also require defining a default format for all numeric column types.  If numeric columns can be sent to handsontable as numeric, then the default render can be set as in the example above.  I'd also like to improve factor handling, it's probably time to revisit the current approach.  I am always open to suggestions and PRs.

**Comment by mbacou** [comment]
Thanks for the bit of htmlwidget() wizardry. This works indeed for now. Could this logic be applied to all types (incl. dates and factors) and patched into rhandsontable (as the default renderer)?

I'm no JS person at all, but came across Oom's V8 package earlier, wondering if that could work with widget JS libraries like handsontable? https://www.opencpu.org/posts/v8-release-0-5/

**Comment by jrowen** [comment]
Thanks for the suggestions. I'll see if we can expand this logic to other
types and also look into V8.
