### ISSUE TITLE
shiny inputs hidden by table

### ISSUE THREAD

**Issue by jrowen** [jrowen/rhandsontable#32]
Details at https://github.com/rstudio/shiny/issues/914

**Comment by jrowen** [comment]
Waiting on a decision from the shiny devs as to whether they will fix in shiny.  For now rhandsontable uses
```
.datepicker {
  z-index: 1000 !important;
}
```
to fix the issue.

**Comment by mbrath** [comment]
The issue now seems to be fixed in shiny already (currently using version 1.0.5). Below you can find my sample code. I had to manually delete the above inserted lines (with z-index) from the "rhandsontable/htmlwidgets/rhandsontable.css" to make this work. If the lines are present, the dateRangeInput is displayed behind the modalDialog.

`library(rhandsontable)
  ui <- fluidPage(
    rHandsontableOutput("tbl")
  )
  
  server <- function(input, output, session) {
    output$tbl <- renderRHandsontable(rhandsontable(matrix(runif(100), ncol = 5)))
    showModal(modalDialog(
      title = "Data Management",
      size = "m",
      easyClose = TRUE,
      
      dateRangeInput("dateRange", "Custom Date Range")
    ))
  }
  
  shinyApp(ui = ui, server = server)`
