### ISSUE TITLE
Add search option

### ISSUE THREAD

**Issue by jrowen** [jrowen/rhandsontable#40]
@cho7tom I made some changes to the context menu options, and I'd appreciate your feedback. You can install using
```
devtools::install_github("jrowen/rhandsontable", ref = "context_menu")
```
and there is a new [example](https://github.com/jrowen/rhandsontable/blob/context_menu/inst/examples/context_menu.R) showing how a user can enable the search functionality.

**Comment by cho7tom** [comment]
Hello Jonathan,

I could successfully test the new context menu options, and it looks great.

   - The *search *option really is a plus to me, especially when it comes
   to analyze relatively big tables.
   - I could not find a way to activate the *column insertion feature*,
   which is light gray as you can see on the screenshot below => is there a
   specific line of code to add so that it works?
   - With the use of rhandsontable I have in mind (i.e. combined within a
   Shiny app), I will personally not use the *comment feature*, as I
   believe there is no way to save this information within a csv file at the
   moment. Is that correct?


Thank you very much for having shared these improvements!

Best,

Thomas

[image: Inline images 1]

**Comment by jrowen** [comment]
See #39 for some background on column add/delete.  It's not available when column types are defined.

You're correct--right now there is no way to save comments.

Thanks for tesring.

**Comment by jrowen** [comment]
I just pushed some updates to the comments functionality.  In particular, you can now specify comments via a `data.frame` or `matrix` and there is a new `_comment` callback in shiny that should allow capturing changes.  This functionality in handsontable is still evolving, and currently you may not be able to capture comment deletes see (https://github.com/handsontable/handsontable/issues/2532).

See the new rhandsontable_comment example in this branch for more details.  Feedback and PRs are welcome.  Thanks.

**Comment by jrowen** [comment]
These updates are now part of the dev version (v0.2.1) and will post to CRAN shortly.  Please re-open this issue if you run into problems with the latest version.  Thanks.

**Comment by AmarendarAndhe** [comment]
Hi Thomas,

Could you please sample UI.R and Server.R code where you have added Search box in rhandsontable

**Comment by AmarendarAndhe** [comment]
@jrowen,

When i run below code:

devtools::install_github("jrowen/rhandsontable", ref = "context_menu")

its giving below error:
`Downloading GitHub repo jrowen/rhandsontable@context_menu
from URL https://api.github.com/repos/jrowen/rhandsontable/zipball/context_menu
Error in stop(github_error(request)) : 404: Not Found
 (404)`

Could you please help me on the same?


Thanks,
Amar

**Comment by sumeda85** [comment]
I can not see the example for the search option. The link does not work
