### ISSUE TITLE
Handsontable doesn't react to other input variables before making the first change to the table

### ISSUE THREAD

**Issue by juancentro** [jrowen/rhandsontable#50]
The scenario is like this:
The values in the table depend on some input variable. If start the app, and change the input variable, the table doesn't react. The way to make it react is to change some value in the table first. After that, changing other input variables makes the table react. But you have to change some value in the table first.
This is in version 0.2.1

**Comment by jrowen** [comment]
Can you share a minimally reproducible example?  It's likely that the table
initialization step is not catching a reactive dependency.  Because this
widget can act as both an input and output, it can sometimes be tricky to
get everything in sync.

**Comment by Rustastra** [comment]
Hi, I have a very similar problem. The values in one h.o.t. depend on values in another one. I tried different approaches, both 
output$hot1=rrhot({if(!is.null(input$hot2))... and observeEvent(input$hot2, and observe... I am close to giving up, because all possible variations work locally, but on shinyapps it just breaks down

**Comment by jrowen** [comment]
I'd suggest taking a look at the some of the examples at
http://jrowen.github.io/rhandsontable/#shiny, particularly the frontier one.

**Comment by jrowen** [comment]
Please let me know if you are still having trouble.  Thanks.
