### ISSUE TITLE
Wrap text in table header

### ISSUE THREAD

**Issue by Atan1988** [jrowen/rhandsontable#58]
Hi Jrowen,

       Thank you for this great package!
        Is there a way that I can have the long text in the table header wrapped?

Thanks,
Allen

**Comment by jrowen** [comment]
I think there are a couple ways to handle this.  One would be to include `<br>` tags in the long text.
```
library(rhandsontable)

DF = data.frame(val = 1:10, big = LETTERS[1:10],
                small = letters[1:10],
                stringsAsFactors = FALSE)

lng_name = paste(strwrap("Really, really, really long name", width = 10), 
                 collapse = "<br>")
rhandsontable(DF, colHeaders = c("A", "B", lng_name)) %>%
  hot_cols(colWidths = 75)
```
Another is to update the css for the table (see [here](http://stackoverflow.com/questions/27791321/wrap-text-on-custom-headers-in-handsontable)).  Since the last option isn't really supported by handsontable, I'll have to think about how this could be implemented.

**Comment by Atan1988** [comment]
Thank you so much! I think the <br>  tag solution is good enough. I used in ggplot labels before, and didn't realize it would work the same in rhandsontable. 

Thanks,
Allen

**Comment by Geoffrey-Guest** [comment]
Thank-you the tag solution worked well for me!

**Comment by gracezhou0501** [comment]
I am wondering how to wrap text in cells instead of table header for rhandsontable. Thanks!
