### ISSUE TITLE
How to download/ save edited tables?

### ISSUE THREAD

**Issue by hiranyakudva** [jrowen/rhandsontable#82]
I have created a Shiny app which takes .csv file as input and generates tabs based on the Grade column.
The code will generate tables in each tab containing only rows of the dataset that match the Grade. These tables are editable. I am trying to download the edited table from the active tabPanel, but I am stuck on what should be the content in the downloadHandler. I have attached the data and code in the text file for reference.
[score.txt](https://github.com/jrowen/rhandsontable/files/292623/score.txt)

**Comment by jrowen** [comment]
This example might help:
https://github.com/jrowen/rhandsontable/tree/master/inst/examples/rhandsontable_datafile

**Comment by jrowen** [comment]
Closing.  Let me know if you still have questions.

**Comment by nvbuuren** [comment]
I am struggling with a similar problem, but I do not have a csv file to load and write to. The rhandsontables are generated on the fly, for example as follows:


```
  output$cov1<-renderUI({
    numericInput("cov1", 
                 "# covariates", 
                 value = 1, min = 0, max = 20)
  })

output$hot6 <- renderRHandsontable({
    DF2 <- data.frame(Label = paste("Covariate",as.integer(1:input$cov1), sep=""),
                     On = rep(TRUE, input$cov1),
                     DataPositions = as.integer(rep.int(1,input$cov1)),
                     Format = c("IL"),
                     stringsAsFactors = FALSE)
    rhandsontable(DF2,width = 500,height = 300) %>%
      hot_col(col = "Format", type = "dropdown", source = c("IL", "IL2", "Real"))
  })

```

I then would like to use the information edited by the users (for example the names of the Covariates) in another part of the app, for example, I want to show the names of the covariates edited by the user in a dropdown menu so that these values/labels can be selected there.  Later, I want to write the full current state of the edited rhandsontables to a 'newly generated' .txt file. Are there any ways that these two things would be possible?
